version: "3"
services:
    docker-database:
        image: postgres:10.4
        container_name: "docker-postgres"
        environment:
        - POSTGRES_DB=db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - PGDATA=/tmp
        - TZ=GMT
        volumes:
        - "./data/postgres:/var/lib/postgresql/data"
        ports:
        - 5432:5432
